### ISSUE TITLE
EAssertionFailed: AI cannot find place for house rangershop (..\ai\KM_AICityPlanner.pas, line 237)

### ISSUE THREAD

**Issue by LpTrip** [Kromster80/knights_province#125] opened 2019-03-07 16:16 UTC
I've reproduced this 2 times already.

Playing "Borders" map, if you play long enough, seems like eventually AI runs out of space and you get this error. Bug report sent via e-mail.

![imagen](https://user-images.githubusercontent.com/36303894/53971108-f6d96000-40da-11e9-89e3-6f9347552aeb.png)

**Comment by Kromster80** [comment] 2019-07-18 07:06
Error was caused by AI trying to build disabled house type. Fixed in one of the older versions.

**Comment by LpTrip** [comment] 2019-08-23 16:03
Issue still occurs on build 7823. Playing against 7 AI (1 horse, 2 strong, 2 mid and 2 weak) on Wheel map.

**Comment by Kromster80** [comment] 2019-12-12 17:10
Finally fixed for real! Can't believe it was triggered on maps with Iron and I didn't test on those..

**Closed by Kromster80** 2019-12-12 17:10 UTC
Labels: area: game, severity: medium, status: fixed, type: bug
